services:
  server:
    extends:
      file: ./docker-services.yml
      service: server
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./server/:/usr/src/app

  client:
    extends:
      file: ./docker-services.yml
      service: client 
    environment:
      # Fixes bug where websocket connection is fixed to default port 3000
      - WDS_SOCKET_PORT=0
      - NODE_ENV=development
    volumes:
      - ./client/:/usr/src/app # Mount client dir to enable development

  reverse_proxy:
    extends:
      file: ./docker-services.yml
      service: nginx

  debug_helper:
    image: busybox

# docker compose -f docker-compose.dev.yml --env-file ./server/.env up
