services:
  server:
    image: outcome-server-dev
    build:
      context: ./server
      dockerfile: dev.Dockerfile

  client:
    image: outcome-client-dev 
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    depends_on:
      - server

  nginx:
    image: nginx:latest@sha256:61face6bf030edce7ef6d7dd66fe452298d6f5f7ce032afdd01683ef02b2b841
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - client # wait for the app container to be started
      - server

  debug_helper:
    image: busybox
