import { uniq } from "lodash";

// Generated from:
// https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/icon.css

export const HAND_PICKED = ["food", "lightning", "black tie"];

export const BUSINESS = [
  "address book",
  "address card",
  "archive",
  "balance scale",
  "birthday cake",
  "book",
  "briefcase",
  "building",
  "bullhorn",
  "bullseye",
  "calculator",
  "calendar",
  "certificate",
  "chart area",
  "chart bar",
  "chart line",
  "chart pie",
  "clipboard",
  "coffee",
  "columns",
  "compass",
  "copy",
  "copyright",
  "cut",
  "edit",
  "envelope",
  "envelope open",
  "envelope square",
  "eraser",
  "fax",
  "file",
  "folder",
  "folder open",
  "globe",
  "industry",
  "paperclip",
  "paste",
  "pen square",
  "percent",
  "phone",
  "phone square",
  "phone volume",
  "registered",
  "save",
  "sitemap",
  "sticky note",
  "suitcase",
  "table",
  "tag",
  "tags",
  "tasks",
  "thumbtack",
  "trademark",
];

export const CODE = [
  "archive",
  "barcode",
  "bath",
  "bug",
  "code",
  "code branch",
  "coffee",
  "file",
  "file code",
  "filter",
  "fire extinguisher",
  "folder",
  "folder open",
  "keyboard",
  "microchip",
  "qrcode",
  "sitemap",
  "terminal",
  "user secret",
  "window close",
  "window maximize",
  "window minimize",
  "window restore",
];
export const COMMUNICATION = [
  "address book",
  "address card",
  "american sign language interpreting",
  "assistive listening systems",
  "at",
  "bell",
  "bell slash",
  "bullhorn",
  "comment",
  "comments",
  "envelope",
  "envelope open",
  "envelope square",
  "fax",
  "inbox",
  "language",
  "microphone",
  "microphone slash",
  "mobile",
  "paper plane",
  "phone",
  "phone square",
  "phone volume",
  "rss",
  "rss square",
  "tty",
  "wifi",
];
export const COMPUTERS = [
  "desktop",
  "download",
  "hdd",
  "headphones",
  "keyboard",
  "laptop",
  "microchip",
  "mobile",
  "plug",
  "power off",
  "print",
  "save",
  "server",
  "tablet",
  "tv",
  "upload",
];
export const CURRENCY = [
  "dollar sign",
  "euro sign",
  "lira sign",
  "pound sign",
  "ruble sign",
  "rupee sign",
  "shekel sign",
  "won sign",
  "yen sign",
];
export const DATE_TIME = [
  "bell",
  "bell slash",
  "calendar",
  "calendar check",
  "calendar minus",
  "calendar plus",
  "calendar times",
  "clock",
  "hourglass",
  "hourglass end",
  "hourglass half",
  "hourglass start",
  "stopwatch",
];
export const DESIGN = [
  "adjust",
  "clone",
  "copy",
  "crop",
  "crosshairs",
  "cut",
  "edit",
  "eraser",
  "eye",
  "eye dropper",
  "eye slash",
  "object group",
  "object ungroup",
  "paint brush",
  "paste",
  "save",
  "tint",
];

export const HANDS_GESTURES = [
  "hand lizard",
  "hand paper",
  "hand peace",
  "hand point down",
  "hand point left",
  "hand point right",
  "hand point up",
  "hand pointer",
  "hand rock",
  "hand scissors",
  "hand spock",
  "handshake",
  "thumbs down",
  "thumbs up",
];
export const HEALTH = [
  "ambulance",
  "h square",
  "heart",
  "heartbeat",
  "hospital",
  "medkit",
  "plus square",
  "stethoscope",
  "user md",
  "wheelchair",
];
export const IMAGES = [
  "adjust",
  "bolt",
  "camera",
  "camera retro",
  "clone",
  "compress",
  "expand",
  "eye",
  "eye dropper",
  "eye slash",
  "file image",
  "film",
  "id badge",
  "id card",
  "image",
  "images",
  "sliders horizontal",
  "tint",
];
export const INTERFACES = [
  "ban",
  "barcode",
  "bars",
  "beer",
  "bell",
  "bell slash",
  "bug",
  "bullhorn",
  "bullseye",
  "calculator",
  "calendar",
  "calendar check",
  "calendar minus",
  "calendar plus",
  "calendar times",
  "certificate",
  "check",
  "check circle",
  "check square",
  "circle",
  "clipboard",
  "clone",
  "cloud",
  "cloud download",
  "cloud upload",
  "coffee",
  "cog",
  "cogs",
  "copy",
  "cut",
  "database",
  "dot circle",
  "download",
  "edit",
  "ellipsis horizontal",
  "ellipsis vertical",
  "envelope",
  "envelope open",
  "eraser",
  "exclamation",
  "exclamation circle",
  "exclamation triangle",
  "eye",
  "eye slash",
  "file",
  "filter",
  "flag",
  "flag checkered",
  "folder",
  "folder open",
  "frown",
  "hashtag",
  "heart",
  "history",
  "home",
  "i cursor",
  "info",
  "info circle",
  "language",
  "magic",
  "meh",
  "microphone",
  "microphone slash",
  "minus",
  "minus circle",
  "minus square",
  "paste",
  "plus",
  "plus circle",
  "plus square",
  "qrcode",
  "question",
  "question circle",
  "quote left",
  "quote right",
  "redo",
  "reply",
  "reply all",
  "rss",
  "rss square",
  "save",
  "search",
  "search minus",
  "search plus",
  "share",
  "share square",
  "sign-in",
  "sign-out",
  "signal",
  "sitemap",
  "sliders horizontal",
  "smile",
  "sort",
  "star",
  "star half",
  "sync",
  "thumbs down",
  "thumbs up",
  "times",
  "times circle",
  "toggle off",
  "toggle on",
  "trash",
  "trophy",
  "undo",
  "upload",
  "user",
  "user circle",
  "wifi",
];
export const LOGISTICS = [
  "box",
  "boxes",
  "clipboard check",
  "clipboard list",
  "dolly",
  "dolly flatbed",
  "pallet",
  "shipping fast",
  "truck",
  "warehouse",
];
export const MAPS = [
  "ambulance",
  "anchor",
  "balance scale",
  "bath",
  "bed",
  "beer",
  "bell",
  "bell slash",
  "bicycle",
  "binoculars",
  "birthday cake",
  "blind",
  "bomb",
  "book",
  "bookmark",
  "briefcase",
  "building",
  "car",
  "coffee",
  "crosshairs",
  "dollar sign",
  "eye",
  "eye slash",
  "fighter jet",
  "fire",
  "fire extinguisher",
  "flag",
  "flag checkered",
  "flask",
  "gamepad",
  "gavel",
  "gift",
  "glass martini",
  "globe",
  "graduation cap",
  "h square",
  "heart",
  "heartbeat",
  "home",
  "hospital",
  "image",
  "images",
  "industry",
  "info",
  "info circle",
  "key",
  "leaf",
  "lemon",
  "life ring",
  "lightbulb",
  "location arrow",
  "low vision",
  "magnet",
  "male",
  "map",
  "map marker",
  "map pin",
  "map signs",
  "medkit",
  "motorcycle",
  "music",
  "newspaper",
  "paw",
  "phone",
  "phone square",
  "phone volume",
  "plane",
  "plug",
  "plus",
  "plus square",
  "print",
  "recycle",
  "road",
  "rocket",
  "search",
  "search minus",
  "search plus",
  "ship",
  "shopping bag",
  "shopping basket",
  "shopping cart",
  "shower",
  "street view",
  "subway",
  "suitcase",
  "tag",
  "tags",
  "taxi",
  "thumbtack",
  "tint",
  "train",
  "tree",
  "trophy",
  "truck",
  "tty",
  "umbrella",
  "university",
  "utensil spoon",
  "utensils",
  "wheelchair",
  "wifi",
  "wrench",
];
export const MEDICAL = [
  "ambulance",
  "band aid",
  "dna",
  "first aid",
  "heart",
  "heartbeat",
  "hospital",
  "hospital symbol",
  "pills",
  "plus",
  "stethoscope",
  "syringe",
  "thermometer",
  "user md",
  "weight",
];
export const OBJECTS = [
  "ambulance",
  "anchor",
  "archive",
  "balance scale",
  "bath",
  "bed",
  "beer",
  "bell",
  "bicycle",
  "binoculars",
  "birthday cake",
  "bomb",
  "book",
  "bookmark",
  "briefcase",
  "bug",
  "building",
  "bullhorn",
  "bullseye",
  "bus",
  "calculator",
  "calendar",
  "camera",
  "camera retro",
  "car",
  "clipboard",
  "cloud",
  "coffee",
  "cog",
  "cogs",
  "compass",
  "copy",
  "cube",
  "cubes",
  "cut",
  "envelope",
  "envelope open",
  "eraser",
  "eye",
  "eye dropper",
  "fax",
  "fighter jet",
  "file",
  "film",
  "fire",
  "fire extinguisher",
  "flag",
  "flag checkered",
  "flask",
  "futbol",
  "gamepad",
  "gavel",
  "gem",
  "gift",
  "glass martini",
  "globe",
  "graduation cap",
  "hdd",
  "headphones",
  "heart",
  "home",
  "hospital",
  "hourglass",
  "image",
  "images",
  "industry",
  "key",
  "keyboard",
  "laptop",
  "leaf",
  "lemon",
  "life ring",
  "lightbulb",
  "lock",
  "lock open",
  "magic",
  "magnet",
  "map",
  "map marker",
  "map pin",
  "map signs",
  "medkit",
  "microchip",
  "microphone",
  "mobile",
  "moon",
  "motorcycle",
  "newspaper",
  "paint brush",
  "paper plane",
  "paperclip",
  "paste",
  "paw",
  "phone",
  "plane",
  "plug",
  "print",
  "puzzle piece",
  "road",
  "rocket",
  "save",
  "search",
  "shopping bag",
  "shopping basket",
  "shopping cart",
  "shower",
  "snowflake",
  "space shuttle",
  "star",
  "sticky note",
  "stopwatch",
  "subway",
  "suitcase",
  "sun",
  "tablet",
  "tag",
  "tags",
  "taxi",
  "thumbtack",
  "train",
  "trash",
  "tree",
  "trophy",
  "truck",
  "tv",
  "umbrella",
  "university",
  "unlock",
  "utensil spoon",
  "utensils",
  "wheelchair",
  "wrench",
];
export const PAYMENTS_SHOPPING = [
  "bell",
  "bookmark",
  "bullhorn",
  "camera",
  "camera retro",
  "cart arrow down",
  "cart plus",
  "certificate",
  "credit card",
  "gem",
  "gift",
  "handshake",
  "heart",
  "key",
  "shopping bag",
  "shopping basket",
  "shopping cart",
  "star",
  "tag",
  "tags",
  "thumbs down",
  "thumbs up",
  "trophy",
];
export const SHAPES = [
  "bookmark",
  "calendar",
  "certificate",
  "circle",
  "cloud",
  "comment",
  "file",
  "folder",
  "heart",
  "map marker",
  "play",
  "square",
  "star",
];

export const SPORTS = [
  "baseball ball",
  "basketball ball",
  "bowling ball",
  "football ball",
  "futbol",
  "golf ball",
  "hockey puck",
  "quidditch",
  "table tennis",
  "volleyball ball",
];

export const VEHICLES = [
  "ambulance",
  "bicycle",
  "bus",
  "car",
  "fighter jet",
  "motorcycle",
  "paper plane",
  "plane",
  "rocket",
  "ship",
  "shopping cart",
  "space shuttle",
  "subway",
  "taxi",
  "train",
  "truck",
  "wheelchair",
];

export const ICONS = uniq([
  ...HAND_PICKED,
  ...BUSINESS,
  ...CODE,
  ...COMMUNICATION,
  ...COMPUTERS,
  ...CURRENCY,
  ...DATE_TIME,
  ...DESIGN,
  ...HANDS_GESTURES,
  ...HEALTH,
  ...IMAGES,
  ...INTERFACES,
  ...LOGISTICS,
  ...MAPS,
  ...MEDICAL,
  ...OBJECTS,
  ...PAYMENTS_SHOPPING,
  ...SHAPES,
  ...SPORTS,
  ...VEHICLES,
]);
