name: Testing stuff

on:
  push:
    branches:
      - master

env:
  CONTAINS_SKIP: ${{ contains(join(github.event.commits.*.message), '#skip') }}
jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES" "$CONTAINS_SKIP"
      - name: Should skip if commits included \#skip 
        if: ${{ ( github.event_name == 'push' && env.CONTAINS_SKIP != 'true' ) }}
        run: echo "Contains skip (true):" "$CONTAINS_SKIP"

